apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: components/apps/operators/acs/overlays/latest
    repoURL: https://github.com/caseyrobb/cluster-config.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
