apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-authentication
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: components/apps/cluster-config/authentication
    repoURL: https://github.com/caseyrobb/cluster-config.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
